<div class="panel-body">
    {{#if visible}}
        <p class="text-muted small">{{helpText}}</p>
        {{#if hasAutoPdf}}
            <p class="text-success small">
                <span class="fas fa-check-circle"></span>
                {{translate 'formatoActaVisitaAutoGenerated' category='ActaVisita'}}
            </p>
        {{/if}}
        <button type="button" class="btn btn-default btn-block" data-action="downloadFormatoActa" data-format="pdf">
            <span class="fas fa-file-pdf"></span> {{pdfLabel}}
        </button>
    {{/if}}
</div>
