<div class="panel-body">
    {{#if visible}}
        <p class="text-muted small">{{helpText}}</p>
        {{#if hasAutoPdf}}
            <p class="text-success small">
                <span class="fas fa-check-circle"></span>
                {{translate 'formatoActaVisitaAutoGenerated' category='ActaVisita'}}
            </p>
            <a class="btn btn-default btn-block" href="{{autoPdfUrl}}" target="_blank" rel="noopener">
                <span class="fas fa-file-pdf"></span> {{autoPdfName}}
            </a>
        {{/if}}
        <button type="button" class="btn btn-default btn-block" data-action="downloadFormatoActa" data-format="docx"{{#unless downloadEnabled}} disabled{{/unless}}>
            <span class="fas fa-file-word"></span> {{wordLabel}}
        </button>
        <button type="button" class="btn btn-default btn-block" data-action="downloadFormatoActa" data-format="pdf"{{#unless downloadEnabled}} disabled{{/unless}}>
            <span class="fas fa-file-pdf"></span> {{pdfLabel}}
        </button>
    {{else}}
        <p class="text-muted small">{{unavailableText}}</p>
    {{/if}}
</div>
